### ISSUE TITLE
Merge the code with deploy

### ISSUE THREAD

**Issue by pabpercab1** [ISPP-G5/NexONG_Backend#132]
At the moment there is a development environment and a beta environment created for the deployment of the S2. The main goal is to merge the two of them to make a project capable of running in development mode (debug) but also in the app engine with the changes of the deploy branch.

**Comment by auroranavas** [comment]
We decided that we are going to investigate deployment with Google Compute Engine. So this does not apply, for now.

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/vS6qZBJ1C0/estimate/10) in Backend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
