### ISSUE TITLE
Deploy for S3

### ISSUE THREAD

**Issue by pabpercab1** [ISPP-G5/NexONG_Backend#143]
Deploy the backend S3 version to Google App Engine.

Consider also using Google VMs as one group suggested.

**Comment by auroranavas** [comment]
After seven hours and a half of research and preparation to deploy our application using Google Compute Engine, we did not succeed. It seems there is a problem with the needed domain, the external IP address and the SSL certificate.

That is why, we will deploy using App Engine again.

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/vS6qZBJ1C0/estimate/18) in Backend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
