### ISSUE TITLE
Sugesstion any post

### ISSUE THREAD

**Issue by pabpercab1** [ISPP-G5/NexONG_Backend#190]
Some users have remarked that is not possible to POST to the suggestions model as an anonym user. Check this, and fix it if you see that does not work.

**Comment by auroranavas** [comment]
I have just checked it, and it lets you make a POST of Suggestion as an anonymous user. I will close the issue then.

**Comment by pabpercab1** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/wmggl1hQlO/estimate/4) in Back PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
